# Projeto de Inteligência Artificial

Compara diferentes métodos de classificação

Métodos a comparar:

- Árvores de decisão
- SVM
- Random Forest

Projeto para a disciplina Inteligência Artificial, 2018 3º Quadrimestre UFABC.

Integrantes do Grupo:
- Luana Ferreira do Nascimento RA 11090115
- Lucas Andrade Cioffi         RA 11024515
- Rodrigo Rominho Mayer        RA 11020716

Os problemas que iremos tratar serão "Heart Disease Data Set" com os dados de Cleveland e "Wine Quality Data Set" com os dados de vinho vermelho.

##### Preparando o dataset

In [40]:
# importa o pandas 
import pandas as pd

# importa o train test split
from sklearn.model_selection import train_test_split

# carrega os datasets
# dataset de doença cardíaca (com diagnósticos de 0 a 4)
# coracao = pd.read_csv("data/processed.cleveland.nonull.csv")
# dataset de doença cardíaca (com diagnósticos 0 ou 1)
coracao = pd.read_csv("data/coracao_nonull_nomagnitude.csv")
vinho = pd.read_csv("data/winequality-red.csv",sep=';')

# ajeita as colunas
coracao.columns  = ["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","num"]

# separa os dados e o target
X_coracao = coracao.drop(["num"], axis=1)
y_coracao = coracao[["num"]]

X_vinho = vinho.drop(["quality"], axis=1)
y_vinho = vinho[["quality"]]

# separa os dados de treinamento e de teste
X_train_coracao, X_test_coracao, y_train_coracao, y_test_coracao = train_test_split(X_coracao, y_coracao, test_size=0.2)
X_train_vinho, X_test_vinho, y_train_vinho, y_test_vinho = train_test_split(X_vinho, y_vinho, test_size=0.2)

##### Visualização dos dados - Heart Disease Data Set

- **age**: Idade
- **sex**: Sexo (1 = masculino, 0 = feminino)
- **cp**: Tipo de dor no peito
    1. Angina típica
    2. Angina atípica
    3. Dor não anginal
    4. Sem sintomas
- **trestbps**: Pressão sanguínea em repouso (mm de Hg)
- **chol**: Colesterol no sangue (mg/dL)
- **fbs**: Açúcar no sangue em jejum > 120 mg/dL (1 = verdadeiro)
- **restecg**: Resultados eletrocardiograma
    0. Normal
    1. Anormalidade nas ondas ST-T
    2. Provável ou definitiva hipertrofia ventricular (esquerda)
- **thalach**: Máxima taxa de batimentos cardíacos (Batimentos/min)
- **exang**: Angina induzida por exercício (1 = verdadeiro)
- **oldpeak**: ST Depression induzida por exercício relativa ao descanso
- **slope**: Taxa de crescimento do segmento ST em exercício de máximo esforço
    1. Crescente
    2. Constante
    3. Decrescente
- **ca**: Número de vias principais coloridas por fluoroscopia (0 - 3)
- **thal**: 3 = normal; 6 = defeito permanente; 7 = defeito reversível
- **num**: [Target] Diagnóstico de doença cardíaca (1 = Verdadeiro)


Segundo a documentação do Heart Disease Data Set:

>  The "goal" field refers to the presence of heart disease
     in the patient.  It is integer valued from 0 (no presence) to 4.
     Experiments with the Cleveland database have concentrated on simply
     attempting to distinguish presence (values 1,2,3,4) from absence (value
     0)
     
Portanto, o treinamento e as previsões foram realizados considerando qualquer valor superior a 0 como diagnóstico positivo.

In [41]:
print(coracao)

      age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0    67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
1    67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
2    37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
3    41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   
4    56.0  1.0  2.0     120.0  236.0  0.0      0.0    178.0    0.0      0.8   
5    62.0  0.0  4.0     140.0  268.0  0.0      2.0    160.0    0.0      3.6   
6    57.0  0.0  4.0     120.0  354.0  0.0      0.0    163.0    1.0      0.6   
7    63.0  1.0  4.0     130.0  254.0  0.0      2.0    147.0    0.0      1.4   
8    53.0  1.0  4.0     140.0  203.0  1.0      2.0    155.0    1.0      3.1   
9    57.0  1.0  4.0     140.0  192.0  0.0      0.0    148.0    0.0      0.4   
10   56.0  0.0  2.0     140.0  294.0  0.0      2.0    153.0    0.0      1.3   
11   56.0  1.0  3.0     130.0  256.0  1.0      2.0  

# Treinamentos

##### Visualização dos dados - Wine Quality Data Set

In [42]:
print(vinho)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5         

##### Treinando com árvores de decisão

Referências para o algoritmo:
- https://scikit-learn.org/stable/modules/tree.html
- https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

In [43]:
from sklearn import tree

# Heart Disease
coracaoTree = tree.DecisionTreeClassifier()
coracaoTree = coracaoTree.fit(X_train_coracao, y_train_coracao)

#Wine Quality
wineTree = tree.DecisionTreeClassifier()
wineTree = wineTree.fit(X_train_vinho, y_train_vinho)

##### Treinando com SVM

Referências para o algoritmo:

- https://scikit-learn.org/stable/modules/svm.html

In [44]:
from sklearn import svm

# Heart Disease
coracaoSvm = svm.SVC()
coracaoSvm = coracaoSvm.fit(X_train_coracao, y_train_coracao)

#Wine Quality
wineSvm = svm.SVC() 
wineSvm = wineSvm.fit(X_train_vinho, y_train_vinho)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


##### Treinando com Random Forest

In [45]:
from sklearn.ensemble import RandomForestClassifier

# Random Forest com 1000 árvores
# Para Heart Disease
rfCoracao = RandomForestClassifier(n_estimators = 20, random_state = 0)
rfCoracao.fit(X_train_coracao, y_train_coracao);

# Para Wine Quality
rfVinho = RandomForestClassifier(n_estimators = 20, random_state = 0)
rfVinho.fit(X_train_vinho, y_train_vinho)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

# Resultados

##### Resultados da árvore de decisão - Heart Disease Data Set

In [46]:
# Realiza a previsão de 20% dos dados (que não foram usados no treinamento)
resultsDT = coracaoTree.predict(X_test_coracao)
resultsDT = resultsDT.tolist()

# Array de resultados reais, utilizado para contagem de previsões corretas
resultadoRealDT = y_test_coracao.values.tolist();

# Contador de previsões corretas
contadorDT = 0

print("N | Previsão | Valor Real")

for x in range(0, len(resultsDT)):
    print(str("{:02d}".format(x + 1)) + "| P: " + str(resultsDT[x]) + "       R: " + str(resultadoRealDT[x][0]))
    if resultsDT[x] == resultadoRealDT[x][0]:
        contadorDT = contadorDT + 1
        
print()
print("Total: " + str(len(resultsDT)))
print("Previstos corretamente: " + str(contadorDT))
print('{0:.2f}'.format((contadorDT/len(resultsDT)) * 100) + "%")

N | Previsão | Valor Real
01| P: 1       R: 1
02| P: 0       R: 0
03| P: 0       R: 1
04| P: 1       R: 1
05| P: 1       R: 0
06| P: 0       R: 0
07| P: 0       R: 1
08| P: 0       R: 0
09| P: 0       R: 0
10| P: 0       R: 0
11| P: 0       R: 0
12| P: 0       R: 0
13| P: 0       R: 0
14| P: 0       R: 0
15| P: 0       R: 0
16| P: 0       R: 0
17| P: 0       R: 1
18| P: 0       R: 0
19| P: 1       R: 1
20| P: 0       R: 0
21| P: 1       R: 1
22| P: 0       R: 1
23| P: 1       R: 1
24| P: 1       R: 1
25| P: 1       R: 1
26| P: 1       R: 1
27| P: 1       R: 1
28| P: 0       R: 1
29| P: 0       R: 0
30| P: 0       R: 0
31| P: 1       R: 1
32| P: 1       R: 0
33| P: 0       R: 0
34| P: 0       R: 0
35| P: 0       R: 0
36| P: 1       R: 0
37| P: 0       R: 0
38| P: 1       R: 1
39| P: 1       R: 1
40| P: 1       R: 1
41| P: 1       R: 1
42| P: 0       R: 1
43| P: 0       R: 0
44| P: 1       R: 1
45| P: 0       R: 0
46| P: 0       R: 1
47| P: 0       R: 0
48| P: 0       R: 1
49| P: 1      

In [56]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

print("Matriz de confusão:")
print(confusion_matrix(y_test_coracao, resultsDT))

print("Acurácia:")
print(accuracy_score(y_test_coracao, resultsDT))

Matriz de confusão:
[[28  4]
 [ 9 19]]
Acurácia:
0.7833333333333333


##### Resultados da árvore de decisão - Wine Quality Data Set

In [48]:
# Realiza a previsão de 20% dos dados (que não foram usados no treinamento)
resultsDTWine = wineTree.predict(X_test_vinho)
resultsDTWine = resultsDTWine.tolist()

# Array de resultados reais, utilizado para contagem de previsões corretas
resultadoRealDTWine = y_test_vinho.values.tolist();

# Contador de previsões corretas
contadorDTWine = 0

print(resultsDTWine)
print(resultadoRealDTWine)

print("N | Previsão | Valor Real")

for x in range(0, len(resultsDTWine)):
    print(str("{:02d}".format(x + 1)) + "| P: " + str(resultsDTWine[x]) + "       R: " + str(resultadoRealDTWine[x][0]))
    if resultsDTWine[x] == resultadoRealDTWine[x][0]:
        contadorDTWine = contadorDTWine + 1
        
print()
print("Total: " + str(len(resultsDTWine)))
print("Previstos corretamente: " + str(contadorDTWine))
print('{0:.2f}'.format((contadorDTWine/len(resultsDTWine)) * 100) + "%")

[5, 6, 6, 6, 5, 8, 6, 5, 6, 6, 6, 4, 6, 6, 7, 6, 5, 8, 6, 6, 5, 4, 5, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 4, 5, 4, 6, 6, 5, 5, 6, 7, 6, 5, 5, 5, 7, 8, 7, 7, 7, 6, 7, 5, 6, 5, 4, 6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 7, 6, 5, 5, 7, 8, 5, 7, 7, 6, 7, 6, 6, 5, 7, 5, 4, 5, 5, 7, 5, 6, 5, 6, 6, 6, 5, 6, 6, 5, 6, 6, 5, 7, 6, 6, 5, 6, 5, 6, 5, 6, 4, 5, 5, 6, 6, 6, 5, 4, 7, 6, 6, 6, 4, 6, 5, 4, 5, 6, 7, 8, 7, 5, 7, 5, 6, 5, 7, 5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 7, 7, 6, 7, 5, 6, 5, 6, 5, 6, 6, 7, 7, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 4, 5, 5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 7, 6, 6, 5, 7, 6, 4, 5, 6, 7, 5, 5, 5, 6, 6, 5, 6, 5, 7, 6, 6, 6, 6, 5, 5, 5, 7, 5, 5, 6, 6, 5, 7, 5, 5, 6, 7, 5, 5, 6, 5, 5, 5, 4, 5, 5, 6, 6, 6, 7, 7, 6, 5, 5, 6, 6, 6, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 6, 5, 7, 6, 6, 6, 4, 6, 7, 6, 6, 5, 5, 5, 7, 7, 6, 5, 5, 5, 5, 5, 5, 5, 7, 7, 6, 5, 6, 5, 5, 5, 5, 7, 5, 6, 5, 4]
[[6], [6], [6], [5], [5], [6], [6], [6]

In [57]:
print("Matriz de confusão:")
print(confusion_matrix(y_test_vinho, resultsDTWine))

print("Acurácia:")
print(accuracy_score(y_test_vinho, resultsDTWine))

Matriz de confusão:
[[ 0  1  0  0  0  0]
 [ 0  3  6  7  0  0]
 [ 0  6 82 30  3  0]
 [ 0  4 38 73 14  3]
 [ 0  1  6 14 23  2]
 [ 0  0  0  3  1  0]]
Acurácia:
0.565625


##### Resultados do SVM - Vinho

In [51]:
# Realiza a previsão de 20% dos dados (que não foram usados no treinamento)
resultsSvmCoracao = coracaoSvm.predict(X_test_coracao)
resultsSvmCoracao = resultsSvmCoracao.tolist()

# Array de resultados reais, utilizado para contagem de previsões corretas
resultadoRealSvmCoracao = y_test_coracao.values.tolist();

# Contador de previsões corretas
contadorSvmCoracao = 0

print(resultsSvmCoracao)
print(resultadoRealSvmCoracao)

print("N | Previsão | Valor Real")

for x in range(0, len(resultsSvmCoracao)):
    print(str("{:02d}".format(x + 1)) + "| P: " + str(resultsSvmCoracao[x]) + "       R: " + str(resultadoRealSvmCoracao[x][0]))
    if resultsSvmCoracao[x] == resultadoRealSvmCoracao[x][0]:
        contadorSvmCoracao = contadorSvmCoracao + 1
        
print()
print("Total: " + str(len(resultsSvmCoracao)))
print("Previstos corretamente: " + str(contadorSvmCoracao))
print('{0:.2f}'.format((contadorSvmCoracao/len(resultsSvmCoracao)) * 100) + "%")

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[1], [0], [1], [1], [0], [0], [1], [0], [0], [0], [0], [0], [0], [0], [0], [0], [1], [0], [1], [0], [1], [1], [1], [1], [1], [1], [1], [1], [0], [0], [1], [0], [0], [0], [0], [0], [0], [1], [1], [1], [1], [1], [0], [1], [0], [1], [0], [1], [1], [0], [0], [1], [1], [0], [0], [1], [0], [0], [0], [1]]
N | Previsão | Valor Real
01| P: 0       R: 1
02| P: 0       R: 0
03| P: 0       R: 1
04| P: 0       R: 1
05| P: 0       R: 0
06| P: 0       R: 0
07| P: 0       R: 1
08| P: 0       R: 0
09| P: 0       R: 0
10| P: 0       R: 0
11| P: 0       R: 0
12| P: 0       R: 0
13| P: 0       R: 0
14| P: 0       R: 0
15| P: 0       R: 0
16| P: 0       R: 0
17| P: 0       R: 1
18| P: 0       R: 0
19| P: 0       R: 1
20| P: 0       R: 0
21| P: 0       R: 1
22| P: 0       R: 1
23| P: 0       R: 1
24| P: 0       R: 1
25| P: 0    

In [58]:
print("Matriz de confusão:")
print(confusion_matrix(y_test_coracao, resultsSvmCoracao))

print("Acurácia:")
print(accuracy_score(y_test_coracao, resultsSvmCoracao))

Matriz de confusão:
[[32  0]
 [28  0]]
Acurácia:
0.5333333333333333


##### Resultados do SVM - Heart Disease Data set

In [54]:
# Realiza a previsão de 20% dos dados (que não foram usados no treinamento)
resultsSvmWine = wineSvm.predict(X_test_vinho)
resultsSvmWine = resultsSvmWine.tolist()

# Array de resultados reais, utilizado para contagem de previsões corretas
resultadoRealSvmWine = y_test_vinho.values.tolist();

# Contador de previsões corretas
contadorSvmWine = 0

print(resultsSvmWine)
print(resultadoRealSvmWine)

print("N | Previsão | Valor Real")

for x in range(0, len(resultsSvmWine)):
    print(str("{:02d}".format(x + 1)) + "| P: " + str(resultsSvmWine[x]) + "       R: " + str(resultadoRealSvmWine[x][0]))
    if resultsSvmWine[x] == resultadoRealSvmWine[x][0]:
        contadorSvmWine = contadorSvmWine + 1
        
print()
print("Total: " + str(len(resultsSvmWine)))
print("Previstos corretamente: " + str(contadorSvmWine))
print('{0:.2f}'.format((contadorSvmWine/len(resultsSvmWine)) * 100) + "%")

[5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 5, 7, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 7, 6, 6, 6, 6, 5, 7, 5, 7, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6, 6, 7, 6, 5, 5, 6, 6, 5, 5, 7, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 6, 5, 6, 6, 6, 7, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 7, 7, 5, 6, 5, 7, 6, 6, 7, 5, 6, 5, 5, 5, 6, 6, 7, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 6, 7, 6, 5, 6, 6, 5, 6, 6, 6, 5, 6, 7, 5, 5, 5, 7, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 5, 6, 7, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 7, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 5, 6, 5, 5, 5, 5, 7, 5, 5, 6, 5, 5, 6, 6, 5, 6, 5, 5, 5, 7, 6, 6, 5, 6, 5, 7, 6, 5, 6, 5, 6, 7, 7, 6, 5, 6, 5, 6, 5, 5, 5, 7, 6, 6, 5, 6, 6, 5, 5, 6, 7, 5, 5, 5, 7]
[[6], [6], [6], [5], [5], [6], [6], [6]

In [59]:
print("Matriz de confusão:")
print(confusion_matrix(y_test_vinho, resultsSvmWine))

print("Acurácia:")
print(accuracy_score(y_test_vinho, resultsSvmWine))

Matriz de confusão:
[[ 0  0  1  0  0  0]
 [ 0  0  6 10  0  0]
 [ 0  0 86 34  1  0]
 [ 0  0 52 75  5  0]
 [ 0  0  8 18 20  0]
 [ 0  0  1  3  0  0]]
Acurácia:
0.565625


##### Resultados do Random Forest - Heart Disease Data Set

In [61]:
# Realiza a previsão de 20% dos dados (que não foram usados no treinamento)
resultsRFCoracao = rfCoracao.predict(X_test_coracao)
resultsRFCoracao = resultsRFCoracao.tolist()

# Array de resultados reais, utilizado para contagem de previsões corretas
resultadoRealRFCoracao = y_test_coracao.values.tolist();

# Contador de previsões corretas
contadorRFCoracao = 0

print("N | Previsão | Valor Real")

for x in range(0, len(resultsRFCoracao)):
    print(str("{:02d}".format(x + 1)) + "| P: " + str(resultsRFCoracao[x]) + "       R: " + str(resultadoRealRFCoracao[x][0]))
    if resultsRFCoracao[x] == resultadoRealRFCoracao[x][0]:
        contadorRFCoracao = contadorRFCoracao + 1
        
print()
print("Total: " + str(len(resultsRFCoracao)))
print("Previstos corretamente: " + str(contadorRFCoracao))
print('{0:.2f}'.format((contadorRFCoracao/len(resultsRFCoracao)) * 100) + "%")

N | Previsão | Valor Real
01| P: 1       R: 1
02| P: 0       R: 0
03| P: 0       R: 1
04| P: 1       R: 1
05| P: 1       R: 0
06| P: 0       R: 0
07| P: 0       R: 1
08| P: 0       R: 0
09| P: 0       R: 0
10| P: 0       R: 0
11| P: 0       R: 0
12| P: 0       R: 0
13| P: 0       R: 0
14| P: 0       R: 0
15| P: 0       R: 0
16| P: 0       R: 0
17| P: 0       R: 1
18| P: 0       R: 0
19| P: 1       R: 1
20| P: 0       R: 0
21| P: 1       R: 1
22| P: 1       R: 1
23| P: 1       R: 1
24| P: 1       R: 1
25| P: 1       R: 1
26| P: 1       R: 1
27| P: 1       R: 1
28| P: 0       R: 1
29| P: 0       R: 0
30| P: 0       R: 0
31| P: 1       R: 1
32| P: 0       R: 0
33| P: 0       R: 0
34| P: 0       R: 0
35| P: 0       R: 0
36| P: 0       R: 0
37| P: 0       R: 0
38| P: 1       R: 1
39| P: 1       R: 1
40| P: 1       R: 1
41| P: 1       R: 1
42| P: 0       R: 1
43| P: 0       R: 0
44| P: 1       R: 1
45| P: 0       R: 0
46| P: 0       R: 1
47| P: 0       R: 0
48| P: 0       R: 1
49| P: 1      

In [62]:
print("Matriz de confusão:")
print(confusion_matrix(y_test_coracao, resultsRFCoracao))

print("Acurácia:")
print(accuracy_score(y_test_coracao, resultsRFCoracao))

Matriz de confusão:
[[30  2]
 [ 8 20]]
Acurácia:
0.8333333333333334


##### Resultados do Random Forest - Wine Quality Data Set

In [63]:
# Realiza a previsão de 20% dos dados (que não foram usados no treinamento)
resultsRFVinho = rfVinho.predict(X_test_vinho)
resultsRFVinho = resultsRFVinho.tolist()

# Array de resultados reais, utilizado para contagem de previsões corretas
resultadoRealRFVinho = y_test_vinho.values.tolist();

# Contador de previsões corretas
contadorRFVinho = 0

print("N | Previsão | Valor Real")

for x in range(0, len(resultsRFVinho)):
    print(str("{:02d}".format(x + 1)) + "| P: " + str(resultsRFVinho[x]) + "       R: " + str(resultadoRealRFVinho[x][0]))
    if resultsRFVinho[x] == resultadoRealRFVinho[x][0]:
        contadorRFVinho = contadorRFVinho + 1
        
print()
print("Total: " + str(len(resultsRFVinho)))
print("Previstos corretamente: " + str(contadorRFVinho))
print('{0:.2f}'.format((contadorRFVinho/len(resultsRFVinho)) * 100) + "%")

N | Previsão | Valor Real
01| P: 5       R: 6
02| P: 6       R: 6
03| P: 6       R: 6
04| P: 6       R: 5
05| P: 5       R: 5
06| P: 6       R: 6
07| P: 6       R: 6
08| P: 5       R: 6
09| P: 5       R: 6
10| P: 6       R: 8
11| P: 5       R: 6
12| P: 5       R: 5
13| P: 6       R: 6
14| P: 6       R: 6
15| P: 7       R: 7
16| P: 5       R: 5
17| P: 5       R: 5
18| P: 6       R: 6
19| P: 6       R: 7
20| P: 5       R: 5
21| P: 5       R: 6
22| P: 5       R: 6
23| P: 5       R: 5
24| P: 6       R: 5
25| P: 5       R: 4
26| P: 6       R: 7
27| P: 5       R: 5
28| P: 5       R: 5
29| P: 6       R: 6
30| P: 5       R: 6
31| P: 5       R: 5
32| P: 6       R: 6
33| P: 6       R: 6
34| P: 5       R: 5
35| P: 6       R: 6
36| P: 6       R: 7
37| P: 6       R: 6
38| P: 6       R: 7
39| P: 6       R: 6
40| P: 5       R: 5
41| P: 5       R: 5
42| P: 5       R: 4
43| P: 5       R: 5
44| P: 6       R: 6
45| P: 6       R: 5
46| P: 5       R: 6
47| P: 6       R: 5
48| P: 7       R: 7
49| P: 6      

In [65]:
print("Matriz de confusão:")
print(confusion_matrix(y_test_vinho, resultsRFVinho))

print("Acurácia:")
print(accuracy_score(y_test_vinho, resultsRFVinho))

Matriz de confusão:
[[ 0  0  1  0  0  0]
 [ 0  0 12  4  0  0]
 [ 0  0 97 24  0  0]
 [ 0  0 40 89  3  0]
 [ 0  0  4 17 25  0]
 [ 0  0  0  4  0  0]]
Acurácia:
0.659375
