# Projeto de Inteligência Artificial

Compara diferentes métodos de classificação

Métodos a comparar:

- Árvores de decisão
- SVM
- Random Forest

Projeto para a disciplina Inteligência Artificial, 2018 3º Quadrimestre UFABC.

Integrantes do Grupo:
- Luana Ferreira do Nascimento RA 11090115
- Lucas Andrade Cioffi         RA 11024515
- Rodrigo Rominho Mayer        RA 11020716

Os problemas que iremos tratar serão "Heart Disease Data Set" com os dados de Cleveland e "Wine Quality Data Set" com os dados de vinho vermelho.

##### Preparando o dataset

In [1]:
# importa o pandas 
import pandas as pd

# importa o train test split
from sklearn.model_selection import train_test_split

# carrega os datasets
# dataset de doença cardíaca (com diagnósticos de 0 a 4)
# coracao = pd.read_csv("data/processed.cleveland.nonull.csv")
# dataset de doença cardíaca (com diagnósticos 0 ou 1)
coracao = pd.read_csv("data/coracao_nonull_nomagnitude.csv")
vinho = pd.read_csv("data/winequality-red.csv",sep=';')

# ajeita as colunas
coracao.columns  = ["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","num"]

# separa os dados e o target
X_coracao = coracao.drop(["num"], axis=1)
y_coracao = coracao[["num"]]

X_vinho = vinho.drop(["quality"], axis=1)
y_vinho = vinho[["quality"]]

# separa os dados de treinamento e de teste
X_train_coracao, X_test_coracao, y_train_coracao, y_test_coracao = train_test_split(X_coracao, y_coracao, test_size=0.2)
X_train_vinho, X_test_vinho, y_train_vinho, y_test_vinho = train_test_split(X_vinho, y_vinho, test_size=0.2)

##### Visualização dos dados - Heart Disease Data Set

- **age**: Idade
- **sex**: Sexo (1 = masculino, 0 = feminino)
- **cp**: Tipo de dor no peito
    1. Angina típica
    2. Angina atípica
    3. Dor não anginal
    4. Sem sintomas
- **trestbps**: Pressão sanguínea em repouso (mm de Hg)
- **chol**: Colesterol no sangue (mg/dL)
- **fbs**: Açúcar no sangue em jejum > 120 mg/dL (1 = verdadeiro)
- **restecg**: Resultados eletrocardiograma
    0. Normal
    1. Anormalidade nas ondas ST-T
    2. Provável ou definitiva hipertrofia ventricular (esquerda)
- **thalach**: Máxima taxa de batimentos cardíacos (Batimentos/min)
- **exang**: Angina induzida por exercício (1 = verdadeiro)
- **oldpeak**: ST Depression induzida por exercício relativa ao descanso
- **slope**: Taxa de crescimento do segmento ST em exercício de máximo esforço
    1. Crescente
    2. Constante
    3. Decrescente
- **ca**: Número de vias principais coloridas por fluoroscopia (0 - 3)
- **thal**: 3 = normal; 6 = defeito permanente; 7 = defeito reversível
- **num**: [Target] Diagnóstico de doença cardíaca (1 = Verdadeiro)


Segundo a documentação do Heart Disease Data Set:

>  The "goal" field refers to the presence of heart disease
     in the patient.  It is integer valued from 0 (no presence) to 4.
     Experiments with the Cleveland database have concentrated on simply
     attempting to distinguish presence (values 1,2,3,4) from absence (value
     0)
     
Portanto, o treinamento e as previsões foram realizados considerando qualquer valor superior a 0 como diagnóstico positivo.

In [2]:
print(coracao)

      age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0    67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
1    67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
2    37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
3    41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   
4    56.0  1.0  2.0     120.0  236.0  0.0      0.0    178.0    0.0      0.8   
5    62.0  0.0  4.0     140.0  268.0  0.0      2.0    160.0    0.0      3.6   
6    57.0  0.0  4.0     120.0  354.0  0.0      0.0    163.0    1.0      0.6   
7    63.0  1.0  4.0     130.0  254.0  0.0      2.0    147.0    0.0      1.4   
8    53.0  1.0  4.0     140.0  203.0  1.0      2.0    155.0    1.0      3.1   
9    57.0  1.0  4.0     140.0  192.0  0.0      0.0    148.0    0.0      0.4   
10   56.0  0.0  2.0     140.0  294.0  0.0      2.0    153.0    0.0      1.3   
11   56.0  1.0  3.0     130.0  256.0  1.0      2.0  

##### Visualização dos dados - Wine Quality Data Set

In [3]:
print(vinho)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5         

## Treinamentos

##### Treinando com Árvores de Decisão

Referências para o algoritmo:
- https://scikit-learn.org/stable/modules/tree.html
- https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

In [4]:
from sklearn import tree

# Heart Disease
coracaoTree = tree.DecisionTreeClassifier()
coracaoTree = coracaoTree.fit(X_train_coracao, y_train_coracao)

#Wine Quality
wineTree = tree.DecisionTreeClassifier()
wineTree = wineTree.fit(X_train_vinho, y_train_vinho)

##### Treinando com SVM

Referências para o algoritmo:

- https://scikit-learn.org/stable/modules/svm.html

In [5]:
from sklearn import svm

# Heart Disease
coracaoSvm = svm.SVC()
coracaoSvm = coracaoSvm.fit(X_train_coracao, y_train_coracao)

#Wine Quality
wineSvm = svm.SVC() 
wineSvm = wineSvm.fit(X_train_vinho, y_train_vinho)

C:\Users\rodri\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


##### Treinando com Random Forest

In [6]:
from sklearn.ensemble import RandomForestClassifier

# Random Forest com 1000 árvores
# Para Heart Disease
rfCoracao = RandomForestClassifier(n_estimators = 20, random_state = 0)
rfCoracao.fit(X_train_coracao, y_train_coracao);

# Para Wine Quality
rfVinho = RandomForestClassifier(n_estimators = 20, random_state = 0)
rfVinho.fit(X_train_vinho, y_train_vinho)

C:\Users\rodri\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
C:\Users\rodri\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
C:\Users\rodri\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

# Resultados

##### Resultados da árvore de decisão - Heart Disease Data Set

In [7]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

y_pred_tree_coracao = coracaoTree.predict(X_test_coracao)

print("Matriz de confusão:")
print(confusion_matrix(y_test_coracao, y_pred_tree_coracao))

print("Acurácia:")
print(accuracy_score(y_test_coracao, y_pred_tree_coracao))

Matriz de confusão:
[[21 14]
 [ 6 19]]
Acurácia:
0.6666666666666666


##### Resultados da árvore de decisão - Wine Quality Data Set

In [8]:
y_pred_tree_vinho = wineTree.predict(X_test_vinho)

print("Matriz de confusão:")
print(confusion_matrix(y_test_vinho, y_pred_tree_vinho))

print("Acurácia:")
print(accuracy_score(y_test_vinho, y_pred_tree_vinho))

Matriz de confusão:
[[ 0  1  0  1  1  0]
 [ 1  1  8  4  0  0]
 [ 0  2 95 25  6  2]
 [ 0  3 32 78 13  3]
 [ 0  1  3 16 21  2]
 [ 0  0  0  0  1  0]]
Acurácia:
0.609375


##### Resultados do SVM - Heart Disease Data set

In [9]:
y_pred_svm_coracao = coracaoSvm.predict(X_test_coracao)

print("Matriz de confusão:")
print(confusion_matrix(y_test_coracao, y_pred_svm_coracao))

print("Acurácia:")
print(accuracy_score(y_test_coracao, y_pred_svm_coracao))

Matriz de confusão:
[[35  0]
 [23  2]]
Acurácia:
0.6166666666666667


##### Resultados do SVM - Wine Quality Data Set

In [10]:
y_pred_svm_vinho = wineSvm.predict(X_test_vinho)

print("Matriz de confusão:")
print(confusion_matrix(y_test_vinho, y_pred_svm_vinho))

print("Acurácia:")
print(accuracy_score(y_test_vinho, y_pred_svm_vinho))

Matriz de confusão:
[[ 0  0  2  1  0  0]
 [ 0  0  7  7  0  0]
 [ 0  0 97 32  1  0]
 [ 0  0 46 76  7  0]
 [ 0  0  8 27  8  0]
 [ 0  0  0  1  0  0]]
Acurácia:
0.565625


##### Resultados do Random Forest - Heart Disease Data Set

In [11]:
y_pred_rf_vinho = rfVinho.predict(X_test_vinho)

print("Matriz de confusão:")
print(confusion_matrix(y_test_vinho, y_pred_rf_vinho))

print("Acurácia:")
print(accuracy_score(y_test_vinho, y_pred_rf_vinho))

Matriz de confusão:
[[  0   1   1   1   0   0]
 [  0   0  10   4   0   0]
 [  0   0 102  27   1   0]
 [  0   0  33  91   5   0]
 [  0   0   2  25  16   0]
 [  0   0   0   1   0   0]]
Acurácia:
0.653125


##### Resultados do Random Forest - Wine Quality Data Set

In [12]:
y_pred_rf_vinho = rfVinho.predict(X_test_vinho)

print("Matriz de confusão:")
print(confusion_matrix(y_test_vinho, y_pred_rf_vinho))

print("Acurácia:")
print(accuracy_score(y_test_vinho, y_pred_rf_vinho))

Matriz de confusão:
[[  0   1   1   1   0   0]
 [  0   0  10   4   0   0]
 [  0   0 102  27   1   0]
 [  0   0  33  91   5   0]
 [  0   0   2  25  16   0]
 [  0   0   0   1   0   0]]
Acurácia:
0.653125
